# export UID=`id -u`; export GID=`id -g`; docker-compose up -d

general:
  build: .
  #image: rosatrancoso/scipy-notebook
  tty: True
  ports:
    - 8888:8888
  volumes:
    - /Users/rosa/Documents:/home/jovyan/work
  environment:
    - JUPYTER_ENABLE_LAB=yes
