channels:
  - conda-forge
dependencies:
  - awscli
  - boto3
  - cartopy
  - geojson
  - geopandas
  - ipyleaflet
  - leafmap
  - nco
  - plotly
  - pygrib
  - rasterio
  - rioxarray
  - wgrib
  - wgrib2
  - wrf-python
  - xarray
